// This file is auto-generated by @hey-api/openapi-ts

export const BalanceItemSchema = {
    properties: {
        asset: {
            type: 'string',
            title: 'Asset'
        },
        free: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Free'
        },
        locked: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Locked'
        }
    },
    type: 'object',
    required: ['asset', 'free', 'locked'],
    title: 'BalanceItem'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BotCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        bot_type: {
            '$ref': '#/components/schemas/BotTypeEnum'
        },
        symbol: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'Symbol'
        },
        base_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Currency'
        },
        quote_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quote Currency'
        },
        investment_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Investment Amount',
            default: '0'
        },
        stop_loss_pct: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stop Loss Pct'
        },
        take_profit_pct: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Take Profit Pct'
        },
        account_id: {
            type: 'string',
            format: 'uuid',
            title: 'Account Id'
        },
        config: {
            additionalProperties: true,
            type: 'object',
            title: 'Config',
            default: {}
        }
    },
    type: 'object',
    required: ['name', 'bot_type', 'account_id'],
    title: 'BotCreate'
} as const;

export const BotLogPublicSchema = {
    properties: {
        event_type: {
            type: 'string',
            maxLength: 50,
            title: 'Event Type'
        },
        level: {
            type: 'string',
            maxLength: 20,
            title: 'Level',
            default: 'info'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload',
            default: {}
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        bot_id: {
            type: 'string',
            format: 'uuid',
            title: 'Bot Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['event_type', 'message', 'id', 'bot_id', 'created_at'],
    title: 'BotLogPublic'
} as const;

export const BotLogsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BotLogPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BotLogsPublic'
} as const;

export const BotPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        bot_type: {
            '$ref': '#/components/schemas/BotTypeEnum'
        },
        symbol: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'Symbol'
        },
        base_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Currency'
        },
        quote_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quote Currency'
        },
        investment_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Investment Amount',
            default: '0'
        },
        stop_loss_pct: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stop Loss Pct'
        },
        take_profit_pct: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Take Profit Pct'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        account_id: {
            type: 'string',
            format: 'uuid',
            title: 'Account Id'
        },
        status: {
            '$ref': '#/components/schemas/BotStatusEnum'
        },
        config: {
            additionalProperties: true,
            type: 'object',
            title: 'Config'
        },
        total_pnl: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Pnl'
        },
        total_pnl_pct: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Pnl Pct'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'bot_type', 'id', 'account_id', 'status', 'config', 'total_pnl', 'total_pnl_pct', 'created_at'],
    title: 'BotPublic'
} as const;

export const BotStatusEnumSchema = {
    type: 'string',
    enum: ['stopped', 'pending', 'running', 'error', 'completed'],
    title: 'BotStatusEnum'
} as const;

export const BotTypeEnumSchema = {
    type: 'string',
    enum: ['spot_grid', 'position_snowball', 'rebalancing', 'spot_dca', 'algo_orders'],
    title: 'BotTypeEnum'
} as const;

export const BotUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        stop_loss_pct: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stop Loss Pct'
        },
        take_profit_pct: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Take Profit Pct'
        }
    },
    type: 'object',
    title: 'BotUpdate'
} as const;

export const BotsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BotPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BotsPublic'
} as const;

export const ExchangeAccountCreateSchema = {
    properties: {
        exchange: {
            '$ref': '#/components/schemas/ExchangeTypeEnum'
        },
        label: {
            type: 'string',
            maxLength: 100,
            title: 'Label'
        },
        api_key: {
            type: 'string',
            minLength: 1,
            title: 'Api Key'
        },
        api_secret: {
            type: 'string',
            minLength: 1,
            title: 'Api Secret'
        },
        extra_params: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra Params'
        }
    },
    type: 'object',
    required: ['exchange', 'label', 'api_key', 'api_secret'],
    title: 'ExchangeAccountCreate'
} as const;

export const ExchangeAccountPublicSchema = {
    properties: {
        exchange: {
            '$ref': '#/components/schemas/ExchangeTypeEnum'
        },
        label: {
            type: 'string',
            maxLength: 100,
            title: 'Label'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        is_valid: {
            type: 'boolean',
            title: 'Is Valid'
        },
        last_verified_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Verified At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['exchange', 'label', 'id', 'is_valid', 'last_verified_at', 'created_at'],
    title: 'ExchangeAccountPublic'
} as const;

export const ExchangeAccountUpdateSchema = {
    properties: {
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'ExchangeAccountUpdate'
} as const;

export const ExchangeAccountsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ExchangeAccountPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ExchangeAccountsPublic'
} as const;

export const ExchangeTypeEnumSchema = {
    type: 'string',
    enum: ['binance', 'upbit', 'kis', 'kiwoom'],
    title: 'ExchangeTypeEnum'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NotificationChannelEnumSchema = {
    type: 'string',
    enum: ['email', 'telegram', 'web_push'],
    title: 'NotificationChannelEnum'
} as const;

export const NotificationDeliveryStatusEnumSchema = {
    type: 'string',
    enum: ['pending', 'sent', 'failed'],
    title: 'NotificationDeliveryStatusEnum'
} as const;

export const NotificationPublicSchema = {
    properties: {
        channel: {
            '$ref': '#/components/schemas/NotificationChannelEnum',
            default: 'email'
        },
        event_type: {
            type: 'string',
            maxLength: 50,
            title: 'Event Type'
        },
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        body: {
            type: 'string',
            title: 'Body'
        },
        is_read: {
            type: 'boolean',
            title: 'Is Read',
            default: false
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload',
            default: {}
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        bot_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bot Id'
        },
        delivery_status: {
            '$ref': '#/components/schemas/NotificationDeliveryStatusEnum'
        },
        attempt_count: {
            type: 'integer',
            title: 'Attempt Count'
        },
        last_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Error'
        },
        sent_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sent At'
        },
        failed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Failed At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['event_type', 'title', 'body', 'id', 'user_id', 'bot_id', 'delivery_status', 'attempt_count', 'last_error', 'sent_at', 'failed_at', 'created_at'],
    title: 'NotificationPublic'
} as const;

export const NotificationSettingsPublicSchema = {
    properties: {
        email_enabled: {
            type: 'boolean',
            title: 'Email Enabled',
            default: true
        },
        telegram_enabled: {
            type: 'boolean',
            title: 'Telegram Enabled',
            default: false
        },
        telegram_chat_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Chat Id'
        },
        notify_bot_start: {
            type: 'boolean',
            title: 'Notify Bot Start',
            default: true
        },
        notify_bot_stop: {
            type: 'boolean',
            title: 'Notify Bot Stop',
            default: true
        },
        notify_bot_error: {
            type: 'boolean',
            title: 'Notify Bot Error',
            default: true
        },
        notify_take_profit: {
            type: 'boolean',
            title: 'Notify Take Profit',
            default: true
        },
        notify_stop_loss: {
            type: 'boolean',
            title: 'Notify Stop Loss',
            default: true
        },
        notify_account_error: {
            type: 'boolean',
            title: 'Notify Account Error',
            default: true
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['user_id', 'updated_at'],
    title: 'NotificationSettingsPublic'
} as const;

export const NotificationSettingsUpdateSchema = {
    properties: {
        email_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email Enabled'
        },
        telegram_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Enabled'
        },
        telegram_chat_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Chat Id'
        },
        notify_bot_start: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notify Bot Start'
        },
        notify_bot_stop: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notify Bot Stop'
        },
        notify_bot_error: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notify Bot Error'
        },
        notify_take_profit: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notify Take Profit'
        },
        notify_stop_loss: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notify Stop Loss'
        },
        notify_account_error: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notify Account Error'
        }
    },
    type: 'object',
    title: 'NotificationSettingsUpdate'
} as const;

export const NotificationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/NotificationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'NotificationsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SubscriptionPlanPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        price_krw: {
            type: 'integer',
            title: 'Price Krw'
        },
        max_bots: {
            type: 'integer',
            title: 'Max Bots'
        },
        max_accounts: {
            type: 'integer',
            title: 'Max Accounts'
        },
        features: {
            additionalProperties: true,
            type: 'object',
            title: 'Features'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'display_name', 'price_krw', 'max_bots', 'max_accounts', 'features', 'is_active', 'created_at'],
    title: 'SubscriptionPlanPublic'
} as const;

export const SubscriptionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        plan_id: {
            type: 'string',
            format: 'uuid',
            title: 'Plan Id'
        },
        status: {
            '$ref': '#/components/schemas/SubscriptionStatusEnum'
        },
        pg_subscription_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pg Subscription Id'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        cancelled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cancelled At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'plan_id', 'status', 'pg_subscription_id', 'started_at', 'expires_at', 'cancelled_at', 'created_at', 'updated_at'],
    title: 'SubscriptionPublic'
} as const;

export const SubscriptionStatusEnumSchema = {
    type: 'string',
    enum: ['active', 'cancelled', 'expired', 'past_due'],
    title: 'SubscriptionStatusEnum'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;