// This file is auto-generated by @hey-api/openapi-ts

export type BalanceItem = {
    asset: string;
    free: string;
    locked: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BotCreate = {
    name: string;
    bot_type: BotTypeEnum;
    symbol?: (string | null);
    base_currency?: (string | null);
    quote_currency?: (string | null);
    investment_amount?: (number | string);
    stop_loss_pct?: (number | string | null);
    take_profit_pct?: (number | string | null);
    account_id: string;
    config?: {
        [key: string]: unknown;
    };
};

export type BotLogPublic = {
    event_type: string;
    level?: string;
    message: string;
    payload?: {
        [key: string]: unknown;
    };
    id: string;
    bot_id: string;
    created_at: string;
};

export type BotLogsPublic = {
    data: Array<BotLogPublic>;
    count: number;
};

export type BotPublic = {
    name: string;
    bot_type: BotTypeEnum;
    symbol?: (string | null);
    base_currency?: (string | null);
    quote_currency?: (string | null);
    investment_amount?: string;
    stop_loss_pct?: (string | null);
    take_profit_pct?: (string | null);
    id: string;
    account_id: string;
    status: BotStatusEnum;
    config: {
        [key: string]: unknown;
    };
    total_pnl: string;
    total_pnl_pct: string;
    created_at: string;
};

export type BotsPublic = {
    data: Array<BotPublic>;
    count: number;
};

export type BotStatusEnum = 'stopped' | 'pending' | 'running' | 'error' | 'completed';

export type BotTypeEnum = 'spot_grid' | 'position_snowball' | 'rebalancing' | 'spot_dca' | 'algo_orders';

export type BotUpdate = {
    name?: (string | null);
    stop_loss_pct?: (number | string | null);
    take_profit_pct?: (number | string | null);
};

export type ExchangeAccountCreate = {
    exchange: ExchangeTypeEnum;
    label: string;
    api_key: string;
    api_secret: string;
    extra_params?: ({
    [key: string]: unknown;
} | null);
};

export type ExchangeAccountPublic = {
    exchange: ExchangeTypeEnum;
    label: string;
    is_active?: boolean;
    id: string;
    is_valid: boolean;
    last_verified_at: (string | null);
    created_at: string;
};

export type ExchangeAccountsPublic = {
    data: Array<ExchangeAccountPublic>;
    count: number;
};

export type ExchangeAccountUpdate = {
    label?: (string | null);
    is_active?: (boolean | null);
};

export type ExchangeTypeEnum = 'binance' | 'upbit' | 'kis' | 'kiwoom';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationChannelEnum = 'email' | 'telegram' | 'web_push';

export type NotificationDeliveryStatusEnum = 'pending' | 'sent' | 'failed';

export type NotificationPublic = {
    channel?: NotificationChannelEnum;
    event_type: string;
    title: string;
    body: string;
    is_read?: boolean;
    payload?: {
        [key: string]: unknown;
    };
    id: string;
    user_id: string;
    bot_id: (string | null);
    delivery_status: NotificationDeliveryStatusEnum;
    attempt_count: number;
    last_error: (string | null);
    sent_at: (string | null);
    failed_at: (string | null);
    created_at: string;
};

export type NotificationSettingsPublic = {
    email_enabled?: boolean;
    telegram_enabled?: boolean;
    telegram_chat_id?: (string | null);
    notify_bot_start?: boolean;
    notify_bot_stop?: boolean;
    notify_bot_error?: boolean;
    notify_take_profit?: boolean;
    notify_stop_loss?: boolean;
    notify_account_error?: boolean;
    user_id: string;
    updated_at: string;
};

export type NotificationSettingsUpdate = {
    email_enabled?: (boolean | null);
    telegram_enabled?: (boolean | null);
    telegram_chat_id?: (string | null);
    notify_bot_start?: (boolean | null);
    notify_bot_stop?: (boolean | null);
    notify_bot_error?: (boolean | null);
    notify_take_profit?: (boolean | null);
    notify_stop_loss?: (boolean | null);
    notify_account_error?: (boolean | null);
};

export type NotificationsPublic = {
    data: Array<NotificationPublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SubscriptionPlanPublic = {
    id: string;
    name: string;
    display_name: string;
    price_krw: number;
    max_bots: number;
    max_accounts: number;
    features: {
        [key: string]: unknown;
    };
    is_active: boolean;
    created_at: string;
};

export type SubscriptionPublic = {
    id: string;
    user_id: string;
    plan_id: string;
    status: SubscriptionStatusEnum;
    pg_subscription_id: (string | null);
    started_at: string;
    expires_at: (string | null);
    cancelled_at: (string | null);
    created_at: string;
    updated_at: string;
};

export type SubscriptionStatusEnum = 'active' | 'cancelled' | 'expired' | 'past_due';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AccountsReadAccountsData = {
    limit?: number;
    skip?: number;
};

export type AccountsReadAccountsResponse = (ExchangeAccountsPublic);

export type AccountsCreateAccountData = {
    requestBody: ExchangeAccountCreate;
};

export type AccountsCreateAccountResponse = (ExchangeAccountPublic);

export type AccountsReadAccountData = {
    id: string;
};

export type AccountsReadAccountResponse = (ExchangeAccountPublic);

export type AccountsUpdateAccountData = {
    id: string;
    requestBody: ExchangeAccountUpdate;
};

export type AccountsUpdateAccountResponse = (ExchangeAccountPublic);

export type AccountsDeleteAccountData = {
    id: string;
};

export type AccountsDeleteAccountResponse = (Message);

export type AccountsGetAccountBalanceData = {
    id: string;
};

export type AccountsGetAccountBalanceResponse = (Array<BalanceItem>);

export type AdminAdminListUsersData = {
    limit?: number;
    skip?: number;
};

export type AdminAdminListUsersResponse = (UsersPublic);

export type AdminAdminGetUserData = {
    userId: string;
};

export type AdminAdminGetUserResponse = (UserPublic);

export type AdminAdminDeactivateUserData = {
    userId: string;
};

export type AdminAdminDeactivateUserResponse = (Message);

export type AdminAdminActivateUserData = {
    userId: string;
};

export type AdminAdminActivateUserResponse = (Message);

export type AdminAdminListBotsData = {
    limit?: number;
    skip?: number;
};

export type AdminAdminListBotsResponse = (BotsPublic);

export type BotsReadBotsData = {
    limit?: number;
    skip?: number;
};

export type BotsReadBotsResponse = (BotsPublic);

export type BotsCreateBotData = {
    requestBody: BotCreate;
};

export type BotsCreateBotResponse = (BotPublic);

export type BotsReadBotData = {
    id: string;
};

export type BotsReadBotResponse = (BotPublic);

export type BotsUpdateBotData = {
    id: string;
    requestBody: BotUpdate;
};

export type BotsUpdateBotResponse = (BotPublic);

export type BotsDeleteBotData = {
    id: string;
};

export type BotsDeleteBotResponse = (Message);

export type BotsReadBotLogsData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type BotsReadBotLogsResponse = (BotLogsPublic);

export type BotsStartBotData = {
    id: string;
};

export type BotsStartBotResponse = (BotPublic);

export type BotsStopBotData = {
    id: string;
};

export type BotsStopBotResponse = (BotPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NotificationsReadNotificationsData = {
    limit?: number;
    skip?: number;
    unreadOnly?: boolean;
};

export type NotificationsReadNotificationsResponse = (NotificationsPublic);

export type NotificationsMarkNotificationAsReadData = {
    id: string;
};

export type NotificationsMarkNotificationAsReadResponse = (NotificationPublic);

export type NotificationsMarkAllNotificationsReadResponse = (Message);

export type NotificationsReadNotificationSettingsResponse = (NotificationSettingsPublic);

export type NotificationsUpdateNotificationSettingsData = {
    requestBody: NotificationSettingsUpdate;
};

export type NotificationsUpdateNotificationSettingsResponse = (NotificationSettingsPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SubscriptionsListPlansResponse = (Array<SubscriptionPlanPublic>);

export type SubscriptionsGetPlanData = {
    planId: string;
};

export type SubscriptionsGetPlanResponse = (SubscriptionPlanPublic);

export type SubscriptionsGetMySubscriptionResponse = ((SubscriptionPublic | null));

export type SubscriptionsCancelMySubscriptionResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);