"""add_exchange_account_bot_subscription_models

Revision ID: 758de2786634
Revises: fe56fa70289e
Create Date: 2026-03-01 09:36:30.793577

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '758de2786634'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptionplan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('price_krw', sa.Integer(), nullable=False),
    sa.Column('max_bots', sa.Integer(), nullable=False),
    sa.Column('max_accounts', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exchangeaccount',
    sa.Column('exchange', sa.Enum('binance', 'upbit', 'kis', 'kiwoom', name='exchangetypeenum'), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('api_secret_enc', sa.Text(), nullable=False),
    sa.Column('extra_params_enc', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersubscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', 'past_due', name='subscriptionstatusenum'), nullable=False),
    sa.Column('pg_subscription_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscriptionplan.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('bot',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('bot_type', sa.Enum('spot_grid', 'position_snowball', 'rebalancing', 'spot_dca', 'algo_orders', name='bottypeenum'), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('base_currency', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('quote_currency', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('investment_amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('stop_loss_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('take_profit_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('stopped', 'pending', 'running', 'error', 'completed', name='botstatusenum'), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('total_pnl_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_fee', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['exchangeaccount.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    op.drop_table('bot')
    op.drop_table('usersubscription')
    op.drop_table('exchangeaccount')
    op.drop_table('subscriptionplan')
    # ### end Alembic commands ###
